default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-41036_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-41036_test

production:
  <<<: *default
  adapter: mysql2
  database: furima-41036_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock
  charset: utf8
  collation: utf8_general_ci